sudo: required

language: go

go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - tip

services:
    - docker

before_install:
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/goimports

script:
    - sh ./goclean.sh
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
    - bash <(curl -s https://codecov.io/bash)
    - go test -bench=. -benchmem ./tradingdays
    - go test -bench=. -benchmem ./twse
    - go test -bench=. -benchmem ./utils
    - sh ./install_all_cmd.sh
    - sh ./build-base.sh
    - sh ./build-mini.sh
    - docker images
    - docker run -it --rm toomore/gogrs:mini sh -c "gogrs example; gogrs realtime; gogrs server -h; gogrs cache; gogrs report;"
